"""Create deliveries table

Revision ID: 72e87b54dee2
Revises: c4b4586c3999
Create Date: 2024-12-10 10:22:01.976612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e87b54dee2'
down_revision = 'c4b4586c3999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('departure_latitude', sa.Float(), nullable=False),
    sa.Column('departure_longitude', sa.Float(), nullable=False),
    sa.Column('arrival_latitude', sa.Float(), nullable=False),
    sa.Column('arrival_longitude', sa.Float(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=False))

    op.drop_table('deliveries')
    # ### end Alembic commands ###
