"""Refactor restaurant model to allow multiple dishes

Revision ID: 89805e2087ac
Revises: cab8db013817
Create Date: 2024-11-29 09:34:59.999354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89805e2087ac'
down_revision = 'cab8db013817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('dish_price')
        batch_op.drop_column('dish_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dish_name', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('dish_price', sa.REAL(), nullable=True))

    # ### end Alembic commands ###
